toc:
- title: Overview
  path: /devices/tech/settings
- title: Design Guidelines
  path: /devices/tech/settings/settings-guidelines
- title: Patterns and Components
  path: /devices/tech/settings/patterns-components
- title: Information Architecture
  path: /devices/tech/settings/info-architecture
- title: Personalized Settings
  path: /devices/tech/settings/personalized
- title: Universal Search
  path: /devices/tech/settings/universal-search
